---
include:
  - board: nice_nano_v2
    shield: ferris_central dongle_display
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: ferris_central
  - board: nice_nano_v2
    shield: ferris_left
    #snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: ferris_right
  - board: nice_nano_v2
    shield: settings_reset
